# version: '1.29.2'
services:
  node:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    environment:
      - PORT=4000
    networks:
      - custom_net
  postgres:
    build: ./database
    ports:
      - '5000:5000'
    environment:
      POSTGRES_PASSWORD: 'password'
    networks:
      - custom_net
networks:
  custom_net:
    driver: bridge
