# version: '1.29.2'
services:
  node:
    build: .
    ports:
      - ${PORT_NODE_HOST}:${PORT_NODE_CONTAINER}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT_NODE_HOST}
    networks:
      - custom_net
    deploy:
      restart_policy:
        condition: any
        # delay: 3s
    # command: nodemon
    volumes:
      - type: bind
        source: ./src
        target: /download/docker_app/src
  postgres:
    build: ./database
    ports:
      - ${PORT_POSTGRES_HOST}:${PORT_POSTGRES_CONTAINER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - custom_net
    volumes:
      - db_data:/usr/docker_app
networks:
  custom_net:
    driver: bridge
volumes:
  db_data:
